### ISSUE TITLE
Please add option to execute something on the commit

### ISSUE THREAD

**Issue by gizmomogwai** [elektronenhirn/oper#7]
Would be great if one could configure this feature e.g. use the git sha + the checkout folder to open gitk there or similar.

More complicated (I guess) but also quite good would be to launch a new terminal session, to investigate the git repository closer.

**Comment by elektronenhirn** [comment]
This is partly something I tried in the early days of oper: I tried to invoke tig on a commit in the same terminal for a deeper analysis. However it turned out to be much more complicated than I thought because I would have to shutdown ncurses, invoke tig and startup ncurses afterwards again.

What I can do quite easily would be support for gitk because I can run it detached from the terminal.

**Comment by gizmomogwai** [comment]
yes thanks .. something configurable non terminal would be fine for me.
i even could do a new gnome-terminal that starts tig automatically.
